apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-manager-backend
  labels:
    app: task-manager-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-manager-backend
  template:
    metadata:
      labels:
        app: task-manager-backend
    spec:
      containers:
      - name: backend
        image: task-manager-app-backend
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          value: postgres://postgres:password@task-manager-db-service:5432/task_manager_db?sslmode=disable