apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-manager-db
  labels:
    app: task-manager-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-manager-db
  template:
    metadata:
      labels:
        app: task-manager-db
    spec:
      containers:
      - name: postgresdb
        image: postgres:16-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_DB
          value: task_manager_db
        volumeMounts:
        - name: db-data-volume
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: db-data-volume
        persistentVolumeClaim:
          claimName: db-pv-claim